In [1]:
import kagglehub
import pandas as pd
import os

# Download datasets
path1 = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")
path2 = kagglehub.dataset_download("rounakbanik/the-movies-dataset")

print("TMDB Path:", path1)
print("Movies Dataset Path:", path2)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/tmdb/tmdb-movie-metadata?dataset_version_number=2...

100%|██████████| 8.89M/8.89M [00:00<00:00, 100MB/s]

Extracting files...

Using Colab cache for faster access to the 'the-movies-dataset' dataset.
TMDB Path: /root/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/versions/2
Movies Dataset Path: /kaggle/input/the-movies-dataset

In [2]:
# TMDB dataset
tmdb_movies = pd.read_csv(os.path.join(path1, "tmdb_5000_movies.csv"))
tmdb_credits = pd.read_csv(os.path.join(path1, "tmdb_5000_credits.csv"))

# Movies dataset
movies_metadata = pd.read_csv(os.path.join(path2, "movies_metadata.csv"), low_memory=False)
credits2 = pd.read_csv(os.path.join(path2, "credits.csv"))
keywords = pd.read_csv(os.path.join(path2, "keywords.csv"))

In [3]:
# Convert IDs to numeric
movies_metadata['id'] = pd.to_numeric(movies_metadata['id'], errors='coerce')
keywords['id'] = pd.to_numeric(keywords['id'], errors='coerce')
credits2['id'] = pd.to_numeric(credits2['id'], errors='coerce')

# Drop null ids
movies_metadata.dropna(subset=['id'], inplace=True)

In [4]:
movies_full = movies_metadata.merge(keywords, on='id')
movies_full = movies_full.merge(credits2, on='id')

movies_full.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,keywords,cast,crew
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357.0,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862.0,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [5]:
merged_movies = movies_full.merge(
    tmdb_movies,
    left_on='original_title',
    right_on='title',
    how='inner'
)

merged_movies.head()

,adult,belongs_to_collection,budget_x,genres_x,homepage_x,id_x,imdb_id,original_language_x,original_title_x,overview_x,...,production_countries_y,release_date_y,revenue_y,runtime_y,spoken_languages_y,status_y,tagline_y,title_y,vote_average_y,vote_count_y
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-10-30,373554033,81.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Toy Story,7.7,5269
1,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710.0,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",1995-11-16,352194034,130.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,No limits. No fears. No substitutes.,GoldenEye,6.6,1174
2,False,NaN,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9087.0,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-11-17,107879496,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Why can't the most powerful man in the world h...,The American President,6.5,195
3,False,NaN,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,10858.0,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-12-22,13681765,192.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",Nixon,7.1,71
4,False,NaN,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,1408.0,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,"[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...",1995-12-22,10017322,119.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Course Has Been Set. There Is No Turning B...,Cutthroat Island,5.7,136

In [6]:
# Example — keep TMDB version
columns_to_drop = [col for col in merged_movies.columns if col.endswith('_y')]

merged_movies.drop(columns=columns_to_drop, inplace=True)

# Rename _x columns
merged_movies.columns = merged_movies.columns.str.replace('_x', '')

In [7]:
merged_movies.shape
merged_movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,keywords,cast,crew
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710.0,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,"[{'id': 701, 'name': 'cuba'}, {'id': 769, 'nam...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de..."
2,False,NaN,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9087.0,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,The American President,False,6.5,199.0,"[{'id': 833, 'name': 'white house'}, {'id': 84...","[{'cast_id': 1, 'character': 'Andrew Shepherd'...","[{'credit_id': '52fe44dac3a36847f80adfa3', 'de..."
3,False,NaN,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,10858.0,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",Nixon,False,7.1,72.0,"[{'id': 840, 'name': 'usa president'}, {'id': ...","[{'cast_id': 1, 'character': 'Richard Nixon', ...","[{'credit_id': '52fe43c59251416c7501d6f3', 'de..."
4,False,NaN,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,1408.0,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Course Has Been Set. There Is No Turning B...,Cutthroat Island,False,5.7,137.0,"[{'id': 911, 'name': 'exotic island'}, {'id': ...","[{'cast_id': 1, 'character': 'Morgan Adams', '...","[{'credit_id': '52fe42f4c3a36847f802f69f', 'de..."

In [8]:
movies = merged_movies[[
    'title',
    'overview',
    'genres',
    'keywords',
    'cast',
    'crew',
    'vote_average'
]]

In [9]:
import ast

def convert(text):
    try:
        return [i['name'] for i in ast.literal_eval(text)]
    except:
        return []

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

/tmp/ipython-input-4293264477.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(convert)
/tmp/ipython-input-4293264477.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(convert)

In [10]:
def get_cast(text):
    try:
        return [i['name'] for i in ast.literal_eval(text)[:3]]
    except:
        return []

movies['cast'] = movies['cast'].apply(get_cast)

/tmp/ipython-input-3568220361.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(get_cast)

In [11]:
movies['overview'] = movies['overview'].fillna('')

movies['tags'] = (
    movies['overview'] + " " +
    movies['genres'].apply(lambda x: " ".join(x)) + " " +
    movies['keywords'].apply(lambda x: " ".join(x)) + " " +
    movies['cast'].apply(lambda x: " ".join(x))
)

/tmp/ipython-input-2237101505.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].fillna('')
/tmp/ipython-input-2237101505.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = (

In [12]:
movies[['title','tags']].head()

                    title                                               tags
0               Toy Story  Led by Woody, Andy's toys live happily in his ...
1               GoldenEye  James Bond must unmask the mysterious head of ...
2  The American President  Widowed U.S. president Andrew Shepherd, one of...
3                   Nixon  An all-star cast powers this epic look at Amer...
4        Cutthroat Island  Morgan Adams and her slave, William Shaw, are ...

In [13]:
movies = movies[movies['tags'].notna()]
movies = movies.reset_index(drop=True)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = cv.fit_transform(movies['tags']).toarray()

In [15]:
vectors.shape

(5110, 5000)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [17]:
similarity[0]

array([1.        , 0.        , 0.039637  , ..., 0.        , 0.06256878,
       0.        ])

In [19]:
def recommend(movie):

    movie_index = movies[movies['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [20]:
recommend('Toy Story')

Toy Story 2
Toy Story 3
Small Soldiers
The 40 Year Old Virgin
The Indian in the Cupboard

In [21]:
def recommend(movie):

    movie = movie.lower()

    if movie not in movies['title'].str.lower().values:
        print("Movie not found!")
        return

    movie_index = movies[movies['title'].str.lower() == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    print("\nTop Recommendations:\n")

    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [22]:
import pickle

pickle.dump(movies, open('movies.pkl','wb'))
pickle.dump(similarity, open('similarity.pkl','wb'))

In [23]:
import requests

def fetch_poster(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=YOUR_API_KEY"
    data = requests.get(url).json()
    return "https://image.tmdb.org/t/p/w500/" + data['poster_path']

In [25]:
from google.colab import files

files.download('movies.pkl')
files.download('similarity.pkl')

In [27]:
print(sorted(similarity[0], reverse=True)[:10])

[np.float64(1.0), np.float64(0.49172252823733775), np.float64(0.4796350187838468), np.float64(0.29371526469766246), np.float64(0.2748812498016867), np.float64(0.2339366755325124), np.float64(0.21854334588326124), np.float64(0.21719012330009815), np.float64(0.20837290442824927), np.float64(0.19760804978495328)]